import { getAnalyticsSummary } from "@/lib/analytics";

const labels:Record<string,string>={page_view:"Page viewed",product_view:"Product viewed",product_click:"Product clicked",quote_click:"Quote clicked",service_click:"Service clicked"};

export default async function AnalyticsPage(){
  const analytics=await getAnalyticsSummary();
  const cards=[["Unique visitors",analytics.uniqueVisitors],["Page views",analytics.totalViews],["Product views",analytics.productViews],["Quote clicks",analytics.quoteClicks]] as const;
  return <div className="space-y-10"><header><p className="text-xs uppercase tracking-[.18em] text-accent">First-party analytics</p><h1 className="mt-2 font-heading text-4xl font-semibold tracking-tight">Visitor & product history</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-muted">Privacy-conscious event history stored in your main database. No passwords, form contents or personal contact details are collected here.</p></header>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label,value])=><div key={label} className="rounded-2xl border border-border bg-white p-6 shadow-sm"><p className="text-xs uppercase tracking-[.14em] text-muted">{label}</p><p className="mt-3 font-mono text-4xl font-semibold">{value}</p></div>)}</div>
    <section><h2 className="font-heading text-2xl font-semibold">Top products</h2><div className="mt-4 overflow-hidden rounded-2xl border border-border bg-white"><table className="w-full text-left text-sm"><thead className="bg-surface-elevated text-xs uppercase tracking-[.12em] text-muted"><tr><th className="p-4">Product</th><th className="p-4">Views</th><th className="p-4">Clicks</th></tr></thead><tbody>{analytics.topProducts.map(item=><tr key={item.slug} className="border-t border-border"><td className="p-4 font-medium">{item.title||item.slug}</td><td className="p-4 font-mono">{item.views}</td><td className="p-4 font-mono">{item.clicks}</td></tr>)}{analytics.topProducts.length===0?<tr><td colSpan={3} className="p-8 text-center text-muted">Analytics will appear after visitors use the website.</td></tr>:null}</tbody></table></div></section>
    <section><h2 className="font-heading text-2xl font-semibold">Recent history</h2><div className="mt-4 overflow-hidden rounded-2xl border border-border bg-white"><table className="w-full text-left text-sm"><thead className="bg-surface-elevated text-xs uppercase tracking-[.12em] text-muted"><tr><th className="p-4">Event</th><th className="p-4">Page / product</th><th className="p-4">Time</th></tr></thead><tbody>{analytics.recentEvents.map(event=><tr key={event.id} className="border-t border-border"><td className="p-4">{labels[event.eventType]||event.eventType}</td><td className="p-4"><p className="font-medium">{event.productTitle||event.path}</p>{event.productTitle?<p className="mt-1 text-xs text-muted">{event.path}</p>:null}</td><td className="p-4 whitespace-nowrap text-xs text-muted">{new Intl.DateTimeFormat("en-GB",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Dhaka"}).format(new Date(event.createdAt))}</td></tr>)}{analytics.recentEvents.length===0?<tr><td colSpan={3} className="p-8 text-center text-muted">No events recorded yet.</td></tr>:null}</tbody></table></div></section>
  </div>;
}
