import { AdminBanner } from "@/components/admin/admin-banner";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select } from "@/components/ui/select";
import { inquiryKindLabels } from "@/lib/constants";
import type { Inquiry, InquiryKind, InquiryPriority, InquiryStatus } from "@/types/inquiries";
import { updateInquiryAction } from "@/app/admin/catalog-actions";

const statuses: InquiryStatus[] = ["new", "in_progress", "contacted", "completed", "archived"];
const priorities: InquiryPriority[] = ["low", "normal", "high", "urgent"];
const kinds: Array<InquiryKind | "all"> = ["all", "quote", "consultation", "service", "identify"];

export function InquiryInbox({ items, path, params }: { items: Inquiry[]; path: string; params: { q?: string; type?: string; status?: string; priority?: string; saved?: string; error?: string } }) {
  const filtered = items.filter(item => (!params.q || `${item.name} ${item.company} ${item.email} ${item.message}`.toLowerCase().includes(params.q.toLowerCase())) && (!params.type || params.type === "all" || item.kind === params.type) && (!params.status || params.status === "all" || item.status === params.status) && (!params.priority || params.priority === "all" || item.priority === params.priority));
  return <div className="space-y-6"><div><p className="text-xs uppercase tracking-[0.18em] text-muted">Inbox</p><h1 className="mt-2 font-heading text-3xl">Inquiries</h1><p className="mt-2 text-sm text-muted">New inquiries are marked clearly until their status is changed.</p></div><AdminBanner saved={params.saved} error={params.error} /><form method="get" className="grid gap-3 sm:grid-cols-4"><Input name="q" defaultValue={params.q} placeholder="Search name, company, email" /><Select name="type" defaultValue={params.type ?? "all"}>{kinds.map(kind => <option key={kind} value={kind}>{kind === "all" ? "All types" : inquiryKindLabels[kind]}</option>)}</Select><Select name="status" defaultValue={params.status ?? "all"}><option value="all">All statuses</option>{statuses.map(status => <option key={status} value={status}>{status.replace("_", " ")}</option>)}</Select><Select name="priority" defaultValue={params.priority ?? "all"}><option value="all">All priorities</option>{priorities.map(priority => <option key={priority} value={priority}>{priority}</option>)}</Select><Button type="submit" variant="outline">Filter</Button></form><div className="overflow-x-auto border border-border"><table className="min-w-full text-left text-sm"><thead className="bg-surface text-xs uppercase tracking-[0.14em] text-muted"><tr><th className="px-4 py-3">Inquiry</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Priority</th><th className="px-4 py-3">Update</th></tr></thead><tbody>{filtered.length === 0 ? <tr><td colSpan={5} className="px-4 py-8 text-muted">No inquiries match these filters.</td></tr> : filtered.map(item => <tr key={item.id} className="border-t border-border"><td className="px-4 py-3"><div className="flex items-center gap-2">{item.status === "new" ? <span className="inline-flex h-2 w-2 rounded-full bg-accent" aria-label="New inquiry" /> : null}<span className={item.status === "new" ? "font-medium" : ""}>{item.name} · {item.company}</span></div><p className="mt-1 text-xs text-muted">{item.email} · {new Date(item.createdAt).toLocaleString()}</p></td><td className="px-4 py-3 text-muted">{inquiryKindLabels[item.kind]}</td><td className="px-4 py-3">{item.status.replace("_", " ")}</td><td className="px-4 py-3">{item.priority}</td><td className="px-4 py-3"><form action={updateInquiryAction} className="flex min-w-64 gap-2"><input type="hidden" name="id" value={item.id} /><input type="hidden" name="returnTo" value={path} /><Select name="status" defaultValue={item.status} aria-label="Inquiry status">{statuses.map(status => <option key={status} value={status}>{status.replace("_", " ")}</option>)}</Select><Select name="priority" defaultValue={item.priority} aria-label="Inquiry priority">{priorities.map(priority => <option key={priority} value={priority}>{priority}</option>)}</Select><Button type="submit" size="sm">Save</Button></form></td></tr>)}</tbody></table></div></div>;
}
