-- Real manufacturer-referenced feed-mill catalog and first-party analytics.
-- Product copy is original; source URLs identify the official reference material.
create table if not exists analytics_events (
  id uuid primary key default gen_random_uuid(),
  visitor_id text not null,
  session_id text not null,
  event_type text not null check (event_type in ('page_view','product_view','product_click','quote_click','service_click')),
  path text not null,
  product_slug text,
  product_title text,
  referrer text,
  user_agent text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists analytics_events_created_idx on analytics_events(created_at desc);
create index if not exists analytics_events_product_idx on analytics_events(product_slug, created_at desc);
create index if not exists analytics_events_visitor_idx on analytics_events(visitor_id, created_at desc);

create table if not exists product_media (
  id uuid primary key default gen_random_uuid(),
  file_name text not null,
  content_type text not null,
  data bytea not null,
  created_at timestamptz not null default now()
);

with catalog as (
  select * from jsonb_to_recordset($catalog$
  [
    {"title":"Optimill Hammer Mill","slug":"optimill-hammer-mill","summary":"High-performance raw-material grinding for coarse and structured animal feed.","description":"The ANDRITZ Optimill is a real industrial hammer-mill reference for controlled particle-size reduction. Its closed rotor, large screen area and configurable grinding arrangement support consistent preparation before mixing and pelleting.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Optimill","sku":"ARM-REF-OPTIMILL","image":"/images/products/optimill-hammer-mill.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/hammer-mills"},
    {"title":"OptiMix Paddle Mixer","slug":"optimix-paddle-mixer","summary":"Fast, hygienic batch mixing for powders, crumbles and liquid additions.","description":"The ANDRITZ OptiMix is a real twin-shaft paddle mixer reference for uniform distribution of nutrients, minerals and liquids. It is designed for fast emptying, accessible cleaning and repeatable batch quality.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"OptiMix","sku":"ARM-REF-OPTIMIX","image":"/images/products/optimix-paddle-mixer.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/mixers/optimix-paddle-mixer"},
    {"title":"FeedMax G Series Pellet Mill","slug":"feedmax-g-series-pellet-mill","summary":"Gear-driven ring-die pelleting for efficient, high-output animal-feed production.","description":"The ANDRITZ FeedMax G series is a real pellet-mill reference available in multiple sizes. Its compact modular layout, adjustable feed distribution and stainless product-contact parts support reliable pelleting and maintainability.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"FeedMax G Series","sku":"ARM-REF-FEEDMAX","image":"/images/products/feedmax-pellet-mill.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/pellet-mills-livestock-feed-and-biofuel"},
    {"title":"Counterflow Pellet Cooler","slug":"andritz-counterflow-pellet-cooler","summary":"Controlled cooling of hot pellets before screening, storage and dispatch.","description":"This real ANDRITZ counterflow cooler reference passes cooling air opposite to product flow for even heat removal. Capacity, airflow and discharge configuration are selected for pellet throughput and ambient conditions.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Counter Flow Cooler","sku":"ARM-REF-COOLER","image":"/images/products/counterflow-cooler.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/counter-flow-cooler"},
    {"title":"Feed Crumbler","slug":"andritz-feed-crumbler","summary":"Adjustable roller crumbling for poultry starter and broiler feed.","description":"The ANDRITZ crumbler is a real equipment reference for reducing cooled pellets into controlled crumble sizes. Feed control and roll adjustment help protect product quality while minimizing unwanted fines.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Crumbler Series","sku":"ARM-REF-CRUMBLER","image":"/images/products/feed-crumbler.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/crumblers-livestock"},
    {"title":"Industrial Air & Dust Filter","slug":"industrial-air-dust-filter","summary":"Process aspiration and dust filtration for safer, cleaner feed production.","description":"ANDRITZ DFAK, DFB, DFE and EFF filters are real industrial references for local and central aspiration duties. The correct model is selected for dust loading, airflow, hygiene and explosion-protection requirements.","category":"industrial-components","brand":"ANDRITZ","model":"DFAK / DFB / DFE / EFF","sku":"ARM-REF-FILTER","image":"/images/products/air-dust-filter.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/air-and-dust-filters-feed-and-biofuel"},
    {"title":"Raw Material Weighing System","slug":"raw-material-weighing-system","summary":"Accurate batch weighing for macro, micro and raw-material dosing.","description":"This real ANDRITZ weighing-system reference supports recipe accuracy before mixing. Hopper volume, load cells, gates and controls are configured to ingredient flow, batch size and production rate.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Feed Weighing Systems","sku":"ARM-REF-WEIGH","image":"/images/products/weighing-system.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/weighing-systems"},
    {"title":"HTST Feed Expander","slug":"htst-feed-expander","summary":"High-temperature short-time treatment for conditioning and pellet performance.","description":"The ANDRITZ feed expander is a real thermal-mechanical conditioning reference. It applies pressure, friction and heat for stabilization, hygienization and improved preparation ahead of pelleting.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Feed Expander","sku":"ARM-REF-EXPANDER","image":"/images/products/feed-expander.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/expander-htst-conditioning"},
    {"title":"CM / CRT Feed Conditioner","slug":"cm-crt-feed-conditioner","summary":"Steam and liquid conditioning with controlled retention before pelleting.","description":"ANDRITZ CM and CRT conditioners are real references for blending heat, moisture and time into feed mash. Adjustable paddles and controlled steam addition prepare material for efficient pelleting and feed hygiene.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"CM / CRT","sku":"ARM-REF-CONDITIONER","image":"/images/products/feed-conditioner.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/conditioners"},
    {"title":"Micro Fluid Addition System","slug":"micro-fluid-addition-system","summary":"Precise addition of enzymes, vitamins, fats, oils and pigments.","description":"The ANDRITZ MFS is a real micro-fluid dosing reference for accurate recipe additions. It can operate stand-alone or integrate with coating systems and plant automation.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"MFS","sku":"ARM-REF-MFS","image":"/images/products/micro-fluid-system.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/micro-fluid-system-mfs"},
    {"title":"Hammer Mill Pocket Feeder","slug":"hammer-mill-pocket-feeder","summary":"Uniform full-width feeding to stabilize hammer-mill load and output.","description":"The ANDRITZ pocket feeder is a real feed-control reference that distributes material consistently across the hammer-mill intake. It supports more stable grinding and effective magnetic separation upstream.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Pocket Feeder","sku":"ARM-REF-FEEDER","image":"/images/products/pocket-feeder.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/pocket-feeder"},
    {"title":"Feed Mill Automation System","slug":"feed-mill-automation-system","summary":"Plant-wide recipe, sequence, alarm and production control.","description":"ANDRITZ automation is a real control-system reference for individual machines or complete feed plants. It coordinates process sequencing, recipe execution, traceability, alarms and operational reporting.","category":"electrical-automation","brand":"ANDRITZ","model":"Process Control System","sku":"ARM-REF-AUTO","image":"/images/products/feed-automation.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/automation-animal-feed"},
    {"title":"Industrial Rotary Valve","slug":"industrial-rotary-valve","summary":"Controlled feeding and air-lock duty in pneumatic and aspiration systems.","description":"This real ANDRITZ rotary-valve reference meters bulk material while maintaining an air seal in vacuum or low-pressure conveying systems. Rotor, clearance and drive selection depend on product and duty.","category":"material-handling","brand":"ANDRITZ","model":"RS Rotary Valve","sku":"ARM-REF-RV","image":"/images/products/rotary-valve.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/rotary-valve"},
    {"title":"Rotary Feed Dresser","slug":"rotary-feed-dresser","summary":"Final cleaning and dressing of dry mash and soft feed ingredients.","description":"The ANDRITZ rotary feed dresser is a real screening reference used to remove oversize material and improve finished-feed consistency before storage or packing.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Rotary Feed Dresser","sku":"ARM-REF-DRESSER","image":"/images/products/rotary-feed-dresser.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/rotary-feed-dresser"},
    {"title":"Air Density Separator","slug":"air-density-separator","summary":"Separation of dense foreign material before the grinding chamber.","description":"The ANDRITZ air-density separator is a real equipment reference that removes heavier contaminants from material entering the hammer mill, protecting downstream machinery and product quality.","category":"feed-mill-machinery","brand":"ANDRITZ","model":"Air Density Separator","sku":"ARM-REF-ADS","image":"/images/products/air-density-separator.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/air-density-separator-feed-and-biofuel"}
  ] $catalog$::jsonb) as x(title text, slug text, summary text, description text, category text, brand text, model text, sku text, image text, source text)
)
insert into products(title,slug,summary,description,category_id,category_slug,brand,model,sku,images,specifications,documents,availability,featured,published,seo_title,seo_description)
select c.title,c.slug,c.summary,c.description,cat.id,c.category,c.brand,c.model,c.sku,
 jsonb_build_array(jsonb_build_object('id',c.slug||'-image','url',c.image,'alt',c.brand||' '||c.model||' — real manufacturer product image','sortOrder',0)),
 jsonb_build_array(jsonb_build_object('id',c.slug||'-scope','group','Application','label','Configuration','value','Engineered to project duty','sortOrder',0)),
 jsonb_build_array(jsonb_build_object('id',c.slug||'-source','title','Official product reference — '||c.brand,'url',c.source,'fileType','Official reference')),
 'made_to_order'::product_availability,false,true,c.title,c.summary
from catalog c join categories cat on cat.slug=c.category
on conflict(slug) do update set title=excluded.title,summary=excluded.summary,description=excluded.description,category_id=excluded.category_id,category_slug=excluded.category_slug,brand=excluded.brand,model=excluded.model,sku=excluded.sku,images=excluded.images,specifications=excluded.specifications,documents=excluded.documents,published=true,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();
