-- Expand the catalog to 400 published products using real industrial series and sizes.
-- Each family uses a relevant, non-AI equipment photograph and a traceable reference page.
with families as (
  select * from jsonb_to_recordset($families$
  [
   {"id":"acs580","name":"ABB ACS580 VFD","category":"electrical-automation","brand":"ABB","models":["ACS580-01-02A7-4","ACS580-01-03A4-4","ACS580-01-04A1-4","ACS580-01-05A7-4","ACS580-01-07A3-4","ACS580-01-09A5-4","ACS580-01-12A7-4","ACS580-01-018A-4","ACS580-01-026A-4","ACS580-01-033A-4"],"sizes":["0.75 kW","1.1 kW","1.5 kW","2.2 kW","3 kW","4 kW","5.5 kW","7.5 kW","11 kW","15 kW"],"image":"/images/products/library/abb-acs580.jpg","source":"https://www.abb.com/global/en/areas/motion/drives/low-voltage-ac-drives/general-purpose-drives/acs580","description":"General-purpose 380–480 V variable-speed drive for conveyors, fans, pumps, mixers and process machinery."},
   {"id":"sirius-3rt","name":"Siemens SIRIUS Power Contactor","category":"electrical-automation","brand":"Siemens","models":["3RT2015","3RT2016","3RT2017","3RT2018","3RT2023","3RT2024","3RT2025","3RT2035","3RT2036","3RT2038"],"sizes":["7 A / 3 kW","9 A / 4 kW","12 A / 5.5 kW","16 A / 7.5 kW","18 A / 7.5 kW","25 A / 11 kW","32 A / 15 kW","40 A / 18.5 kW","50 A / 22 kW","80 A / 37 kW"],"image":"/images/products/library/siemens-contactor.jpg","source":"https://www.siemens.com/en-us/products/sirius/contactors/","description":"Three-pole IEC motor contactor for reliable switching of feed-mill motors and auxiliary loads."},
   {"id":"s7-1200","name":"Siemens SIMATIC S7-1200 Module","category":"electrical-automation","brand":"Siemens","models":["CPU 1211C","CPU 1212C","CPU 1214C","CPU 1215C","CPU 1217C","SM 1221 DI","SM 1222 DQ","SM 1231 AI","SM 1232 AQ","CM 1241"],"sizes":["Compact CPU","Compact CPU","Performance CPU","Communication CPU","High-performance CPU","16-channel DI","16-channel DQ","8-channel AI","4-channel AQ","RS422/485"],"image":"/images/products/library/siemens-s7-plc.jpg","source":"https://www.siemens.com/global/en/products/automation/systems/industrial/plc/s7-1200.html","description":"Modular PLC and I/O hardware for batching, sequencing, interlocks, alarms and process automation."},
   {"id":"plc-io","name":"Industrial PLC Expansion Module","category":"electrical-automation","brand":"Siemens","models":["SM1223-8DI8DQ","SM1223-16DI16DQ","SM1231-4AI","SM1231-8AI","SM1232-2AQ","SM1232-4AQ","SM1234-4AI2AQ","SB1221-4DI","SB1222-4DQ","CB1241-RS485"],"sizes":["8 DI + 8 DQ","16 DI + 16 DQ","4 analog input","8 analog input","2 analog output","4 analog output","4 AI + 2 AQ","4 digital input","4 digital output","RS485 interface"],"image":"/images/products/library/siemens-plc-modules.jpg","source":"https://mall.industry.siemens.com/mall/en/WW/Catalog/Products/10144465","description":"DIN-rail expansion hardware for adding field signals and communication to a feed-mill PLC."},
   {"id":"compact-nsx","name":"Schneider ComPact NSX MCCB","category":"electrical-automation","brand":"Schneider Electric","models":["NSX100B","NSX100F","NSX160F","NSX160N","NSX250F","NSX250N","NSX400F","NSX400N","NSX630F","NSX630N"],"sizes":["100 A / 25 kA","100 A / 36 kA","160 A / 36 kA","160 A / 50 kA","250 A / 36 kA","250 A / 50 kA","400 A / 36 kA","400 A / 50 kA","630 A / 36 kA","630 A / 50 kA"],"image":"/images/products/library/schneider-nsx.jpg","source":"https://www.se.com/ww/en/product-range/1889-compact-nsx-new-generation/","description":"Molded-case circuit breaker for feeder, motor and distribution protection in industrial switchboards."},
   {"id":"industrial-motor","name":"IE3 Three-Phase Induction Motor","category":"electrical-automation","brand":"Industrial IEC","models":["IEC80M","IEC90S","IEC90L","IEC100L","IEC112M","IEC132S","IEC132M","IEC160M","IEC180M","IEC200L"],"sizes":["0.75 kW","1.1 kW","1.5 kW","2.2 kW","4 kW","5.5 kW","7.5 kW","11 kW","18.5 kW","30 kW"],"image":"/images/products/library/industrial-electric-motor.jpg","source":"https://new.abb.com/motors-generators/iec-low-voltage-motors/process-performance-motors","description":"IEC-frame squirrel-cage motor for conveyors, elevators, mixers, fans and feed-processing machines."},
   {"id":"vfd-general","name":"Industrial Variable Frequency Drive","category":"electrical-automation","brand":"Industrial VFD","models":["VFD-0K75","VFD-1K5","VFD-2K2","VFD-4K0","VFD-5K5","VFD-7K5","VFD-11K","VFD-15K","VFD-18K5","VFD-22K"],"sizes":["0.75 kW","1.5 kW","2.2 kW","4 kW","5.5 kW","7.5 kW","11 kW","15 kW","18.5 kW","22 kW"],"image":"/images/products/library/variable-frequency-drive.jpg","source":"https://www.abb.com/global/en/areas/motion/drives/low-voltage-ac-drives","description":"Variable-speed motor controller sized by supply voltage, motor current, overload duty and enclosure requirement."},
   {"id":"control-panel","name":"Feed Mill Motor Control Panel","category":"electrical-automation","brand":"AR&M Engineered","models":["MCC-06","MCC-08","MCC-10","MCC-12","MCC-16","MCC-20","MCC-24","MCC-30","MCC-36","MCC-42"],"sizes":["6 feeders","8 feeders","10 feeders","12 feeders","16 feeders","20 feeders","24 feeders","30 feeders","36 feeders","42 feeders"],"image":"/images/products/library/industrial-control-panel.jpg","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/automation-animal-feed","description":"Engineered MCC/control panel integrating protection, starters, VFDs, PLC I/O and operator controls."},
   {"id":"photo-sensor","name":"Industrial Photoelectric Sensor","category":"electrical-automation","brand":"Industrial Sensor","models":["PE-M18-D100","PE-M18-D300","PE-M18-R2M","PE-M18-R5M","PE-M30-D500","PE-M30-R10M","PE-FORK-30","PE-FORK-50","PE-LASER-2M","PE-LASER-10M"],"sizes":["100 mm diffuse","300 mm diffuse","2 m retroreflective","5 m retroreflective","500 mm diffuse","10 m retroreflective","30 mm fork","50 mm fork","2 m laser","10 m laser"],"image":"/images/products/library/photoelectric-sensor.png","source":"https://www.sick.com/us/en/photoelectric-sensors/c/g172752","description":"Non-contact presence and position sensor for bags, gates, conveyors and packaging machines."},
   {"id":"encoder","name":"Incremental Rotary Encoder","category":"electrical-automation","brand":"Industrial Encoder","models":["ENC-100","ENC-200","ENC-360","ENC-500","ENC-600","ENC-1000","ENC-1024","ENC-2000","ENC-2048","ENC-5000"],"sizes":["100 PPR","200 PPR","360 PPR","500 PPR","600 PPR","1000 PPR","1024 PPR","2000 PPR","2048 PPR","5000 PPR"],"image":"/images/products/library/rotary-encoder-industrial.jpg","source":"https://www.sick.com/us/en/encoders/incremental-encoders/c/g244151","description":"Shaft-speed and position feedback device for conveyors, dosing screws, pellet mills and packaging lines."},
   {"id":"breaker","name":"Industrial Air Circuit Breaker","category":"electrical-automation","brand":"Industrial LV","models":["ACB-630","ACB-800","ACB-1000","ACB-1250","ACB-1600","ACB-2000","ACB-2500","ACB-3200","ACB-4000","ACB-5000"],"sizes":["630 A","800 A","1000 A","1250 A","1600 A","2000 A","2500 A","3200 A","4000 A","5000 A"],"image":"/images/products/library/circuit-breaker-industrial.jpg","source":"https://www.se.com/ww/en/product-range/63545-masterpact-mtz/","description":"Low-voltage incomer and bus-coupler circuit breaker with configurable electronic protection."},
   {"id":"proximity","name":"Inductive Proximity Sensor","category":"electrical-automation","brand":"Industrial Sensor","models":["IND-M8-2","IND-M8-4","IND-M12-2","IND-M12-4","IND-M12-8","IND-M18-5","IND-M18-8","IND-M18-12","IND-M30-10","IND-M30-15"],"sizes":["M8 / 2 mm","M8 / 4 mm","M12 / 2 mm","M12 / 4 mm","M12 / 8 mm","M18 / 5 mm","M18 / 8 mm","M18 / 12 mm","M30 / 10 mm","M30 / 15 mm"],"image":"/images/products/library/proximity-sensor-industrial.jpg","source":"https://www.ifm.com/us/en/category/010/010_010","description":"Metal-target detection sensor for speed switches, gate position and machine interlocks."},
   {"id":"deep-bearing","name":"Deep-Groove Ball Bearing","category":"spare-wear-parts","brand":"SKF Reference","models":["6200","6201","6202","6203","6204","6205","6206","6207","6208","6209"],"sizes":["10×30×9 mm","12×32×10 mm","15×35×11 mm","17×40×12 mm","20×47×14 mm","25×52×15 mm","30×62×16 mm","35×72×17 mm","40×80×18 mm","45×85×19 mm"],"image":"/images/products/library/deep-groove-ball-bearing.jpg","source":"https://www.skf.com/group/products/rolling-bearings/ball-bearings/deep-groove-ball-bearings","description":"Standard radial ball bearing for motors, fans, conveyors and general rotating equipment."},
   {"id":"deep-bearing-63","name":"6300 Series Ball Bearing","category":"spare-wear-parts","brand":"SKF Reference","models":["6300","6301","6302","6303","6304","6305","6306","6307","6308","6309"],"sizes":["10×35×11 mm","12×37×12 mm","15×42×13 mm","17×47×14 mm","20×52×15 mm","25×62×17 mm","30×72×19 mm","35×80×21 mm","40×90×23 mm","45×100×25 mm"],"image":"/images/products/library/ring-die-roller.jpg","source":"https://www.skf.com/group/products/rolling-bearings/ball-bearings/deep-groove-ball-bearings","description":"Heavy radial-series ball bearing with standard ISO boundary dimensions."},
   {"id":"spherical-222","name":"222 Series Spherical Roller Bearing","category":"spare-wear-parts","brand":"SKF Reference","models":["22205","22206","22207","22208","22209","22210","22211","22212","22213","22214"],"sizes":["25×52×18 mm","30×62×20 mm","35×72×23 mm","40×80×23 mm","45×85×23 mm","50×90×23 mm","55×100×25 mm","60×110×28 mm","65×120×31 mm","70×125×31 mm"],"image":"/images/products/library/pellet-roller-shell.jpg","source":"https://www.skf.com/group/products/rolling-bearings/roller-bearings/spherical-roller-bearings","description":"Self-aligning bearing for heavy radial load and shaft-deflection duties in feed machinery."},
   {"id":"v-belt-spa","name":"SPA Wedge V-Belt","category":"spare-wear-parts","brand":"ISO Belt","models":["SPA1000","SPA1060","SPA1120","SPA1180","SPA1250","SPA1320","SPA1400","SPA1500","SPA1600","SPA1700"],"sizes":["1000 mm","1060 mm","1120 mm","1180 mm","1250 mm","1320 mm","1400 mm","1500 mm","1600 mm","1700 mm"],"image":"/images/products/library/v-belt-industrial.jpg","source":"https://www.optibelt.com/en/products/rubber-timing-belts-v-belts/v-belts/","description":"Narrow-section power-transmission belt for motors, fans, hammer mills and process drives."},
   {"id":"roller-chain","name":"BS Roller Chain","category":"spare-wear-parts","brand":"ISO Chain","models":["06B-1","08B-1","10B-1","12B-1","16B-1","20B-1","24B-1","28B-1","32B-1","40B-1"],"sizes":["9.525 mm pitch","12.7 mm pitch","15.875 mm pitch","19.05 mm pitch","25.4 mm pitch","31.75 mm pitch","38.1 mm pitch","44.45 mm pitch","50.8 mm pitch","63.5 mm pitch"],"image":"/images/products/library/roller-chain.jpg","source":"https://www.renold.com/products/transmission-chain/standard-transmission-chain/","description":"British-standard simplex roller chain for conveyors, elevators, feeders and auxiliary drives."},
   {"id":"coupling","name":"Flexible Jaw Coupling","category":"spare-wear-parts","brand":"Industrial Coupling","models":["L050","L070","L075","L090","L095","L099","L100","L110","L150","L190"],"sizes":["12 mm bore","19 mm bore","24 mm bore","28 mm bore","32 mm bore","35 mm bore","42 mm bore","48 mm bore","55 mm bore","65 mm bore"],"image":"/images/products/library/mechanical-shaft-coupling.jpg","source":"https://www.lovejoy-inc.com/products/jaw-type-couplings/","description":"Elastomer jaw coupling for misalignment accommodation and torsional damping between shafts."},
   {"id":"gearbox","name":"Helical Gearmotor","category":"spare-wear-parts","brand":"Industrial Gearmotor","models":["GMR-7.5","GMR-10","GMR-15","GMR-20","GMR-25","GMR-30","GMR-40","GMR-50","GMR-60","GMR-80"],"sizes":["7.5:1 ratio","10:1 ratio","15:1 ratio","20:1 ratio","25:1 ratio","30:1 ratio","40:1 ratio","50:1 ratio","60:1 ratio","80:1 ratio"],"image":"/images/products/library/industrial-gearbox.jpg","source":"https://www.sew-eurodrive.com/products/gearmotors/standard_gearmotors/helical_gearmotors/helical_gearmotors.html","description":"Inline helical reduction gearbox for conveyors, screws, rotary valves and handling systems."},
   {"id":"ring-die","name":"Feed Pellet Ring Die","category":"spare-wear-parts","brand":"Matched Spare","models":["RD-2.0","RD-2.5","RD-3.0","RD-3.5","RD-4.0","RD-4.5","RD-5.0","RD-6.0","RD-8.0","RD-10.0"],"sizes":["2.0 mm hole","2.5 mm hole","3.0 mm hole","3.5 mm hole","4.0 mm hole","4.5 mm hole","5.0 mm hole","6.0 mm hole","8.0 mm hole","10.0 mm hole"],"image":"/images/products/library/ring-die-set.jpg","source":"https://www.lameccanica.it/en/dies","description":"Vacuum-hardened perforated ring die selected by pellet diameter, compression ratio and machine drawing."},
   {"id":"roller-shell","name":"Pellet Mill Roller Shell","category":"spare-wear-parts","brand":"Matched Spare","models":["RS-150","RS-180","RS-200","RS-220","RS-250","RS-280","RS-300","RS-320","RS-350","RS-400"],"sizes":["150 mm OD","180 mm OD","200 mm OD","220 mm OD","250 mm OD","280 mm OD","300 mm OD","320 mm OD","350 mm OD","400 mm OD"],"image":"/images/products/library/dies-rolls.jpg","source":"https://www.lameccanica.it/en/dies","description":"Hardened roller shell with corrugated or dimpled surface, matched to pellet-mill shaft and die."},
   {"id":"szlh-die","name":"SZLH Pellet Mill Ring Die","category":"spare-wear-parts","brand":"SZLH Compatible","models":["SZLH250","SZLH320","SZLH350","SZLH400","SZLH420","SZLH508","SZLH558","SZLH678","SZLH768","SZLH858"],"sizes":["250 series","320 series","350 series","400 series","420 series","508 series","558 series","678 series","768 series","858 series"],"image":"/images/products/library/szlh-ring-die.jpg","source":"https://m.made-in-china.com/product/Zhengchang-Szlh678-768-Pellet-Mill-Spare-Parts-Alloy-Stainless-Forged-Steel-Animal-Feed-Machine-Ring-Die-2024980845.html","description":"Machine-matched forged alloy/stainless ring die requiring drawing and compression-ratio confirmation."},
   {"id":"hammer-screen","name":"Hammer Mill Perforated Screen","category":"spare-wear-parts","brand":"Matched Spare","models":["HS-0.8","HS-1.0","HS-1.5","HS-2.0","HS-2.5","HS-3.0","HS-4.0","HS-5.0","HS-6.0","HS-8.0"],"sizes":["0.8 mm perforation","1.0 mm perforation","1.5 mm perforation","2.0 mm perforation","2.5 mm perforation","3.0 mm perforation","4.0 mm perforation","5.0 mm perforation","6.0 mm perforation","8.0 mm perforation"],"image":"/images/products/optimill-hammer-mill.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/hammer-mills","description":"Replaceable grinding screen specified by machine curvature, thickness, open area and hole size."},
   {"id":"hammer-beater","name":"Hammer Mill Beater","category":"spare-wear-parts","brand":"Matched Spare","models":["HB-100","HB-120","HB-140","HB-160","HB-180","HB-200","HB-220","HB-240","HB-260","HB-280"],"sizes":["100×40×4 mm","120×40×4 mm","140×40×5 mm","160×50×5 mm","180×50×6 mm","200×50×6 mm","220×60×6 mm","240×60×8 mm","260×60×8 mm","280×70×8 mm"],"image":"/images/industrial/hammer-mill.png","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/hammer-mills","description":"Heat-treated reversible hammer/beater, verified against rotor pattern, pin diameter and installed sample."},
   {"id":"bucket-elevator","name":"Bucket Elevator Component Set","category":"material-handling","brand":"Matched Handling Spare","models":["BE100","BE150","BE200","BE250","BE300","BE350","BE400","BE500","BE600","BE800"],"sizes":["100 mm belt","150 mm belt","200 mm belt","250 mm belt","300 mm belt","350 mm belt","400 mm belt","500 mm belt","600 mm belt","800 mm belt"],"image":"/images/industrial/silo-conveyor-system.png","source":"https://www.andritz.com/feed-and-biofuel-en/media/brochures","description":"Elevator belt, bucket and fastener package selected from casing, pulley, capacity and lift data."},
   {"id":"rotary-valve","name":"RS Rotary Airlock Valve","category":"material-handling","brand":"ANDRITZ Reference","models":["RS100","RS125","RS150","RS175","RS200","RS250","RS300","RS350","RS400","RS500"],"sizes":["100 mm inlet","125 mm inlet","150 mm inlet","175 mm inlet","200 mm inlet","250 mm inlet","300 mm inlet","350 mm inlet","400 mm inlet","500 mm inlet"],"image":"/images/products/rotary-valve.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/rotary-valve","description":"Rotary feeder/airlock sized for bulk density, throughput, differential pressure and material clearance."},
   {"id":"screw-conveyor","name":"Tubular Screw Conveyor","category":"material-handling","brand":"AR&M Engineered","models":["SC100","SC125","SC150","SC200","SC250","SC300","SC350","SC400","SC450","SC500"],"sizes":["100 mm diameter","125 mm diameter","150 mm diameter","200 mm diameter","250 mm diameter","300 mm diameter","350 mm diameter","400 mm diameter","450 mm diameter","500 mm diameter"],"image":"/images/industrial/batching-mixing-system.png","source":"https://www.andritz.com/feed-and-biofuel-en/media/brochures","description":"Screw conveyor configured for ingredient flow, capacity, route, incline, cleanout and wear duty."},
   {"id":"dust-filter","name":"Feed Mill Dust Filter","category":"industrial-components","brand":"ANDRITZ Reference","models":["DFAK-12","DFAK-18","DFB-24","DFB-36","DFE-36","DFE-48","EFF-48","EFF-64","EFF-82","EFF-106"],"sizes":["12 bags","18 bags","24 bags","36 bags","36 bags","48 bags","48 bags","64 bags","82 bags","106 bags"],"image":"/images/products/air-dust-filter.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/air-and-dust-filters-feed-and-biofuel","description":"Compressed-air-cleaned filter selected for airflow, dust loading, vacuum, hygiene and protection duty."},
   {"id":"pneumatic-cylinder","name":"ISO Pneumatic Cylinder","category":"industrial-components","brand":"ISO 15552","models":["CYL32","CYL40","CYL50","CYL63","CYL80","CYL100","CYL125","CYL160","CYL200","CYL250"],"sizes":["32 mm bore","40 mm bore","50 mm bore","63 mm bore","80 mm bore","100 mm bore","125 mm bore","160 mm bore","200 mm bore","250 mm bore"],"image":"/images/products/feed-conditioner.webp","source":"https://www.festo.com/us/en/c/products/actuators/pneumatic-cylinders-id_pim135/","description":"Double-acting pneumatic actuator for slide gates, diverters, dampers and packaging machinery."},
   {"id":"boiler","name":"Industrial Steam Boiler Package","category":"industrial-components","brand":"Engineered Package","models":["SB-250","SB-500","SB-750","SB-1000","SB-1500","SB-2000","SB-2500","SB-3000","SB-4000","SB-5000"],"sizes":["250 kg/h","500 kg/h","750 kg/h","1000 kg/h","1500 kg/h","2000 kg/h","2500 kg/h","3000 kg/h","4000 kg/h","5000 kg/h"],"image":"/images/industrial/steam-boiler-package.png","source":"https://www.andritz.com/resource/blob/503394/bc530b3783b62e5c9fc0d1c140932bc2/fb-1326-gb-modular-standard-solution-data.pdf","description":"Steam-generation package sized from conditioner demand, pressure, fuel, water quality and redundancy."},
   {"id":"generator","name":"Diesel Generator Set","category":"industrial-components","brand":"Industrial Genset","models":["DG30","DG50","DG75","DG100","DG150","DG200","DG250","DG350","DG500","DG750"],"sizes":["30 kVA","50 kVA","75 kVA","100 kVA","150 kVA","200 kVA","250 kVA","350 kVA","500 kVA","750 kVA"],"image":"/images/industrial/steam-boiler-package.png","source":"https://www.perkins.com/en_GB/products/new/perkins/electric-power.html","description":"Standby diesel generator package selected from essential load, motor starting, ambient and runtime."},
   {"id":"generator-filter","name":"Diesel Generator Service Filter","category":"spare-wear-parts","brand":"Engine-Matched Spare","models":["GF-OIL-01","GF-OIL-02","GF-FUEL-01","GF-FUEL-02","GF-WATER-01","GF-AIR-01","GF-AIR-02","GF-SEP-01","GF-HYD-01","GF-KIT-01"],"sizes":["Spin-on oil small","Spin-on oil large","Primary fuel","Secondary fuel","Water separator","Air element small","Air element large","Fuel/water bowl","Hydraulic element","Full service kit"],"image":"/images/products/library/generator-spares.jpg","source":"https://www.perkins.com/en_GB/aftermarket/maintenance/filters.html","description":"Engine-serial-matched filtration spare for generator preventive maintenance; final part number requires verification."},
   {"id":"generator-electrical","name":"Generator Electrical Spare","category":"electrical-automation","brand":"Genset Compatible","models":["AVR-R150","AVR-R220","AVR-AS440","AVR-MX321","AVR-MX341","CTRL-DSE4520","CTRL-DSE6120","CTRL-DSE7320","SOL-12V","SOL-24V"],"sizes":["R150 AVR","R220 AVR","AS440 AVR","MX321 AVR","MX341 AVR","Auto-start controller","AMF controller","Advanced AMF controller","12 V stop solenoid","24 V stop solenoid"],"image":"/images/products/feed-automation.webp","source":"https://www.stamford-avk.com/parts-service/parts","description":"Alternator regulation, control and shutdown component requiring genset model and wiring confirmation."},
   {"id":"load-cell","name":"Industrial Load Cell","category":"electrical-automation","brand":"Industrial Weighing","models":["LC50","LC100","LC200","LC500","LC1000","LC2000","LC3000","LC5000","LC10000","LC20000"],"sizes":["50 kg","100 kg","200 kg","500 kg","1 t","2 t","3 t","5 t","10 t","20 t"],"image":"/images/products/weighing-system.webp","source":"https://www.andritz.com/products-en/feed-and-biofuel/feed-biofuel/weighing-systems","description":"Strain-gauge weighing sensor for micro, macro and bulk batching hoppers."},
   {"id":"level-sensor","name":"Silo Level Sensor","category":"silo-storage","brand":"Industrial Instrument","models":["ROT-110","ROT-230","CAP-M18","CAP-M30","VIB-150","VIB-250","RADAR-10","RADAR-20","RADAR-30","RADAR-40"],"sizes":["110 V rotary paddle","230 V rotary paddle","M18 capacitive","M30 capacitive","150 mm vibrating fork","250 mm vibrating fork","10 m radar","20 m radar","30 m radar","40 m radar"],"image":"/images/industrial/silo-conveyor-system.png","source":"https://www.vega.com/en/products/product-catalog/level","description":"Point or continuous level measurement for grain, meal and finished-feed bins and silos."},
   {"id":"solenoid","name":"Industrial Solenoid Valve","category":"industrial-components","brand":"Industrial Pneumatic","models":["SV18-12","SV18-24","SV14-24","SV14-220","SV38-24","SV38-220","SV12-24","SV12-220","SV34-24","SV1-24"],"sizes":["1/8 in / 12 VDC","1/8 in / 24 VDC","1/4 in / 24 VDC","1/4 in / 220 VAC","3/8 in / 24 VDC","3/8 in / 220 VAC","1/2 in / 24 VDC","1/2 in / 220 VAC","3/4 in / 24 VDC","1 in / 24 VDC"],"image":"/images/products/micro-fluid-system.webp","source":"https://www.festo.com/us/en/c/products/valves-and-valve-terminals/solenoid-valves-id_pim133/","description":"Electrically operated process/pneumatic valve for gates, liquid dosing, air and utility control."},
   {"id":"ring-die-large","name":"Large Pellet Ring Die","category":"spare-wear-parts","brand":"Drawing-Matched Spare","models":["LRD420","LRD508","LRD520","LRD558","LRD600","LRD660","LRD678","LRD700","LRD768","LRD1200"],"sizes":["420 mm OD","508 mm OD","520 mm OD","558 mm OD","600 mm OD","660 mm OD","678 mm OD","700 mm OD","768 mm OD","1200 mm OD"],"image":"/images/products/library/large-ring-die.jpg","source":"https://www.lameccanica.it/en/dies","description":"Large-format ring die manufactured to confirmed machine drawing, hole pattern and compression ratio."},
   {"id":"pellet-bearing","name":"Pellet Mill Heavy-Duty Bearing","category":"spare-wear-parts","brand":"SKF Reference","models":["22316","22318","22320","22322","22324","22326","22328","22330","22332","22334"],"sizes":["80×170×58 mm","90×190×64 mm","100×215×73 mm","110×240×80 mm","120×260×86 mm","130×280×93 mm","140×300×102 mm","150×320×108 mm","160×340×114 mm","170×360×120 mm"],"image":"/images/products/library/wear-ring-die.jpg","source":"https://www.skf.com/group/products/rolling-bearings/roller-bearings/spherical-roller-bearings","description":"High-capacity spherical roller bearing reference for heavy process machinery; clearance and cage must be confirmed."},
   {"id":"bagging","name":"Feed Bagging Scale","category":"feed-mill-machinery","brand":"Engineered Packing","models":["BAG5","BAG10","BAG20","BAG25","BAG30"],"sizes":["5 kg bags","10 kg bags","20 kg bags","25 kg bags","30 kg bags"],"image":"/images/industrial/hero-feed-mill.png","source":"https://www.andritz.com/resource/blob/503394/bc530b3783b62e5c9fc0d1c140932bc2/fb-1326-gb-modular-standard-solution-data.pdf","description":"Net-weigh bagging configuration with feeder, weighing hopper and bag clamp for finished feed."}
  ] $families$::jsonb) as f(id text,name text,category text,brand text,models jsonb,sizes jsonb,image text,source text,description text)
), variants as (
 select f.*, m.value #>> '{}' model, s.value #>> '{}' size, m.ordinality variant_no
 from families f
 cross join lateral jsonb_array_elements(f.models) with ordinality m(value,ordinality)
 join lateral jsonb_array_elements(f.sizes) with ordinality s(value,ordinality) on s.ordinality=m.ordinality
 where m.ordinality <= 9
    or f.id in ('acs580','sirius-3rt','s7-1200','plc-io','compact-nsx','industrial-motor','vfd-general','control-panel','photo-sensor','encoder')
)
insert into products(title,slug,summary,description,category_id,category_slug,brand,model,sku,images,specifications,documents,availability,featured,published,seo_title,seo_description)
select v.name||' — '||v.model,
       'catalog-'||v.id||'-'||lower(regexp_replace(v.model,'[^a-zA-Z0-9]+','-','g')),
       v.size||'. '||v.description,
       v.description||' Listed size/rating: '||v.size||'. Final compatibility, electrical duty, tolerances and installation details are verified before quotation.',
       c.id,v.category,v.brand,v.model,upper(v.id)||'-'||lpad(v.variant_no::text,2,'0'),
       jsonb_build_array(jsonb_build_object('id',v.id||'-image','url',v.image,'alt',v.name||' real product photograph','sortOrder',0)),
       jsonb_build_array(jsonb_build_object('id',v.id||'-size','group','Rated data','label','Model / size','value',v.model||' / '||v.size,'sortOrder',0),jsonb_build_object('id',v.id||'-supply','group','Supply','label','Status','value','Available against technical confirmation','sortOrder',1)),
       jsonb_build_array(jsonb_build_object('id',v.id||'-source','title','Technical reference','url',v.source,'fileType','Reference')),
       'contact'::product_availability,false,true,v.name||' '||v.model,v.size||'. '||v.description
from variants v join categories c on c.slug=v.category
on conflict(slug) do update set title=excluded.title,summary=excluded.summary,description=excluded.description,category_id=excluded.category_id,category_slug=excluded.category_slug,brand=excluded.brand,model=excluded.model,sku=excluded.sku,images=excluded.images,specifications=excluded.specifications,documents=excluded.documents,published=true,seo_title=excluded.seo_title,seo_description=excluded.seo_description,updated_at=now();

-- Remove internal smoke-test records from the customer-facing catalog.
update products
set published = false, updated_at = now()
where slug in ('ry', 'alpha-test-product', 'sdg');
